version: '3.4'

x-common-env-vars:
  - &postgres-url
    "OBTBOT_DB_URL=postgres://obr:${POSTGRES_PASSWORD}@postgres:5432/obr"
  - &postgres-db
    POSTGRES_DATABASE=obr
  - &postgres-user
    POSTGRES_USER=obr
  - &postgres-password
    POSTGRES_PASSWORD

services:

  bot:
    restart: "no"
    image: obr
    build: .
    environment:
      - *postgres-url
      - OBRBOT_TOKEN
    depends_on:
      - postgres-db
    ports:
      - "3000:3000"

  admin-panel:
    image: obr
    ports:
      - "8000:8000"
    environment:
      - *postgres-url
      - "OBRBOT_REDIS_URL=redis://redis"
    depends_on:
      - postgres-db
      - redis-cache

  postgres-db:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      - *postgres-db
      - *postgres-user
      - *postgres-password
    ports:
      - "5432:5432"
    volumes:  # Persist the db data
      - database-data:/var/lib/postgresql/data

  postgres-backup:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - /var/opt/pgbackups:/backups
    depends_on:
      - postgres-db
    environment:
      - *postgres-db
      - *postgres-user
      - *postgres-password
      - POSTGRES_HOST=postgres
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=3928

  redis-cache:
    image: redis:latest
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache-data:/data

volumes:
  database-data:
  cache-data: